/*!
 * p5-livesketch builder
 * @author amekusa (https://amekusa.com)
 */

const // Built-in modules
	fs   = require('fs'), // File system
	path = require('path'), // Path helper
	proc = require('child_process'), // Process manager
	util = require('util'); // Utilities

const // NPM modules
	yargs    = require('yargs'),
	chalk    = require('chalk'),
	inquirer = require('inquirer'),
	del      = require('del'),
	bsync    = require('browser-sync'),
	rollup   = require('rollup');

const // Gulp modules
	$        = require('gulp'),
	$if      = require('gulp-if'),
	$rename  = require('gulp-rename');

const // Local modules
	Task = require('./lib/Task'),
	logger = require('./lib/Logger').global;

// Directory structure
const dirs = {
	src:     'sketches',
	app:     'app',
	dist:    'dist',
	themes:  'themes',
	modules: 'node_modules'
}
// Commandline options
// @see https://yargs.js.org/docs/#api-reference-optionskey-opt
const argv = yargs.options({
	sketch: {
		alias:       's',
		type:        'string',
		description: 'Sketch to run or compile'
	},
	theme: {
		alias:       't',
		type:        'string',
		default:     dirs.themes+'/default',
		description: 'Theme directory'
	},
	browser: {
		alias:       'b',
		type:        'string',
		default:     'default',
		description: 'Browser to open the app'
	},
	clean: {
		alias:       'c',
		type:        'boolean',
		default:     false,
		description: 'Clean mode'
	},
	watch: {
		alias:       'w',
		type:        'boolean',
		default:     false,
		description: 'Watch mode'
	},
	dev: {
		alias:       'd',
		type:        'boolean',
		default:     false,
		description: 'Development mode'
	}
}).argv;

 ////////////////
////  Utilities

function error(name, msg = '') {
	let r = new Error({
		SketchMissing: `There is no sketch`,
		NoSuchSketch: `No such sketch`,
		ThemeMissing: `Theme missing`
	}[name] + (msg ? ` ${msg}` : ''));
	r.name = chalk.red(name);
	return r;
}

function log(...args) {
	logger.log(...args);
}

function debug(...args) {
	if (!argv.dev) return;
	logger.debug(...args);
}

 ////////////
////  Tasks

const cleanApp = new Task('clean:app', (resolve, reject) => {
	return del([dirs.app+'/**', '!'+dirs.app]).then(resolve).catch(reject);
});

const cleanDist = new Task('clean:dist', (resolve, reject) => {
	return del([dirs.dist+'/**', '!'+dirs.dist]).then(resolve).catch(reject);
});

const clean = new Task('clean', [cleanApp, cleanDist]);

/**
 * Resolves the path to the sketch to build
 */
const resolveSketch = new Task('resolve:sketch', (resolve, reject) => {
	if (argv.sketch) {
		let sketch = path.join(dirs.src, argv.sketch);
		return fs.existsSync(sketch) ? resolve(sketch) : reject(error('NoSuchSketch', `as ${argv.sketch}`));
	}
	let files = fs.readdirSync(dirs.src, { withFileTypes: true });
	let options = [];
	for (let iFile of files) {
		if (!iFile.isFile()) continue;
		options.push(iFile.name);
	}
	if (!options.length) return reject(error('SketchMissing'));
	if (options.length == 1) return resolve(path.join(dirs.src, options[0]));

	logger.suppress(true);
	return inquirer.prompt({
		type:    'list',
		name:    'sketch',
		message: 'Which sketch do you want to run?',
		choices: options

	}).then(answer => {
		logger.unsuppress();
		return resolve(path.join(dirs.src, answer.sketch));
	});
});

/**
 * Resolves the path to the theme
 */
const resolveTheme = new Task('resolve:theme', (resolve, reject) => {
	let paths = [
		argv.theme,
		path.join(dirs.themes, argv.theme),
		path.join(dirs.src, argv.theme),
		path.join(dirs.modules, argv.theme)
	];
	for (let iPath of paths) {
		if (fs.existsSync(iPath)) return resolve(iPath);
	}
	return reject(error('ThemeMissing'));
});

/**
 * Build the sketch with rollup
 * @requires rollup
 * @see https://rollupjs.org/guide/en/
 */
const buildSketchRollup = new Task('build:sketch:rollup', (resolve, reject) => {
	let input = {
		input: resolveSketch.resolved,
		context: 'window', // Maybe unnecessary
		treeshake: false
		/* NOTE: Treeshaking is the rollup's feature that performs
		 * culling unreachable code to reduce the size of the result.
		 * Because the sketch itself is handled by p5js core which is
		 * never reached from rollup, we need to turn this feature off
		 * to avoid the entire sketch getting culled.
		 **/
	}, output = {
		file: dirs.app+'/sketch.js',
		format: 'iife', // For browsers
		exports: 'none',
		// Comment out the wrapper function generated by rollup
		banner: '/*', intro:  '*/',
		outro:  '/*', footer: '*/'
		/* NOTE: To get p5js running in "global mode",
		 * we need to expose the p5 functions (such as setup, draw, etc.) to global.
		 * This trick is a quite hacky, but the easiest way to achieve it.
		 **/
	};
	if (argv.watch) {
		let expr = `[${chalk.cyan('Rollup')}]`;
		let options = input;
		options.output = output;
		return rollup.watch(options).on('event', ev => {
			switch (ev.code) {
			case 'START':
				log(expr+` Watching files...`);
				break;
			case 'BUNDLE_END':
				log(expr+` Build ${chalk.green('Success')}`, ev.result.watchFiles);
				break;
			case 'END':
				return resolve(ev);
			case 'ERROR':
				return reject(ev);
			}
		});
	}
	return rollup.rollup(input).then(bundle => {
		return bundle.write(output).then(resolve).catch(reject);
	}).catch(reject);

}, [resolveSketch]);
if (argv.clean) buildSketchRollup.addDep(cleanApp);

/**
 * @deprecated
 * Build the sketch with webpack
 * @requires webpack-stream
 */
const buildSketchWebpack = new Task('build:sketch:webpack', (resolve, reject) => {
	const webpack  = require('webpack-stream');
	let config = {
		mode: argv.dev ? 'development' : 'production',
		resolve: {
			alias: {
				sketches: path.resolve(__dirname, 'sketches/'),
				assets:   path.resolve(__dirname, 'assets/')
			}
		},
		entry: resolveSketch.resolved,
		output: {
			filename: 'sketch.js'
		}
	};
	return $.src(resolveSketch.resolved)
		.pipe(webpack(config))
		.pipe($.dest(dirs.app))
		.on('end', resolve);

}, [resolveSketch]);
if (argv.clean) buildSketchWebpack.addDep(cleanApp);

/**
 * Build the sketch
 */
const buildSketch = new Task('build:sketch', [buildSketchRollup]);

/**
 * Build the theme
 */
const buildTheme = new Task('build:theme', (resolve, reject) => {
	return $.src(path.join(resolveTheme.resolved, '*'))
		.pipe($.dest(dirs.app))
		.on('end', resolve);

}, [resolveTheme]);
if (argv.clean) buildTheme.addDep(cleanApp);

/**
 * Build p5js
 */
const buildP5 = new Task('build:p5', (resolve, reject) => {
	let base = dirs.modules+'/p5/lib/';
	return $.src([
			base+'p5.min.js',
			base+'addons/*.min.js'
		], {base: base})
		.pipe($.dest(dirs.app))
		.on('end', resolve);
});
if (argv.clean) buildP5.addDep(cleanApp);

/**
 * Build the app
 */
const build = new Task('build', [buildSketch, buildTheme, buildP5]);

/**
 * Run the app with Browsersync
 * @see https://www.browsersync.io/docs/options
 */
const app = new Task('app', (resolve, reject) => {
	return bsync.init({
		watch: true, // This should activate live reload
		browser: argv.browser,
		server: {
			baseDir: dirs.app,
			index: 'index.html'
		}
	}, resolve);
});
if (argv.watch) app.addDep(build);

 ///////////////////
////  Public Tasks
exports.build = build;
exports.buildSketch = buildSketch;
exports.app = app;
exports.clean = clean;
